### ISSUE TITLE
AROAnalyzer: java.lang.NullPointerException when exporting CSV/JSON file

### ISSUE THREAD

**Issue by Thongngo** [attdevsupport/ARO#14]
Dear Dev Team,

I got an issue with the latest version ARO Analyzer (4.1.1) for Mac OS when exporting CSV/JSON file from final result. Previous version of ARO Analyzer still works well.
I've already tried on 3 various of mac os machines (10.10.4) and even reinstalled OS, still fail.
=============
java.lang.NullPointerException
at com.att.aro.main.AROAnalysisResultsTab.saveCSV(Unknown Source)
at com.att.aro.main.AROAnalysisResultsTab.exportCSVFileToFileSystem(Unknown Source)
at com.att.aro.main.ApplicationResourceOptimizer$26.actionPerformed(Unknown Source)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
at java.awt.Component.processMouseEvent(Component.java:6516)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
at java.awt.Component.processEvent(Component.java:6281)
at java.awt.Container.processEvent(Container.java:2229)
at java.awt.Component.dispatchEventImpl(Component.java:4872)
at java.awt.Container.dispatchEventImpl(Container.java:2287)
at java.awt.Component.dispatchEvent(Component.java:4698)
=============
Now I'm using previous version for substitute.
Thanks for hard working.

**Comment by bn153x** [comment]
Hi,

What is the exact version that you are using?
What versions of Java do you have?

Can you supply a zip of the trace folder.


Barry

On Jul 16, 2015, at 12:02 AM, Thongngo <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Dev Team,

I got an issue with the latest version ARO Analyzer (4.1.1) for Mac OS when exporting CSV/JSON file from final result. Previous version of ARO Analyzer still works well.

I've already tried on 3 various of mac os machines (10.10.4) and even reinstalled OS, still fail.

java.lang.NullPointerException
at com.att.aro.main.AROAnalysisResultsTab.saveCSV(Unknown Source)
at com.att.aro.main.AROAnalysisResultsTab.exportCSVFileToFileSystem(Unknown Source)
at com.att.aro.main.ApplicationResourceOptimizer$26.actionPerformed(Unknown Source)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
at java.awt.Component.processMouseEvent(Component.java:6516)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
at java.awt.Component.processEvent(Component.java:6281)
at java.awt.Container.processEvent(Container.java:2229)
at java.awt.Component.dispatchEventImpl(Component.java:4872)
at java.awt.Container.dispatchEventImpl(Container.java:2287)

at java.awt.Component.dispatchEvent(Component.java:4698)

Now I'm using previous version for substitute.
Thanks for hard working.

**Comment by diarec** [comment]
thanks guys...
